
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MULT = 34;
  public static final int INT = 17;
  public static final int MINUS = 36;
  public static final int STATIC = 11;
  public static final int SEMICOLON = 21;
  public static final int AND = 33;
  public static final int LT = 31;
  public static final int LP = 24;
  public static final int COMMA = 22;
  public static final int CLASS = 15;
  public static final int RP = 25;
  public static final int PLUS = 35;
  public static final int MAIN = 14;
  public static final int IF = 2;
  public static final int THIS = 16;
  public static final int DOT = 23;
  public static final int EOF = 0;
  public static final int BOOLEAN = 18;
  public static final int LC = 26;
  public static final int LB = 28;
  public static final int RETURN = 12;
  public static final int EQUAL = 30;
  public static final int TRUE = 5;
  public static final int NEW = 10;
  public static final int error = 1;
  public static final int RC = 27;
  public static final int RB = 29;
  public static final int NUMBER = 37;
  public static final int VOID = 20;
  public static final int NEG = 32;
  public static final int ELSE = 3;
  public static final int WHILE = 4;
  public static final int PUBLIC = 13;
  public static final int EXTENDS = 7;
  public static final int SYSO = 8;
  public static final int STRING = 19;
  public static final int FALSE = 6;
  public static final int LENGTH = 9;
  public static final int IDENTIFIER = 38;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "WHILE",
  "TRUE",
  "FALSE",
  "EXTENDS",
  "SYSO",
  "LENGTH",
  "NEW",
  "STATIC",
  "RETURN",
  "PUBLIC",
  "MAIN",
  "CLASS",
  "THIS",
  "INT",
  "BOOLEAN",
  "STRING",
  "VOID",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "LP",
  "RP",
  "LC",
  "RC",
  "LB",
  "RB",
  "EQUAL",
  "LT",
  "NEG",
  "AND",
  "MULT",
  "PLUS",
  "MINUS",
  "NUMBER",
  "IDENTIFIER"
  };
}

